### PR TITLE
prometheus: release 0.13.2

### PR DESCRIPTION
**Pull request by lucab**
## 0.13.2

- Bug fix: Fix compilation on 32-bit targets (#446)

### CODE REVIEW

**Comment by lucab** [comment]
I had to bundle a toolchain bump and some fixes for new warnings as some of our dependencies started requiring a more recent compiler to build.

**Review by yinheli — APPROVED** [review]

**Review by BusyJay — APPROVED** [review]

**Review by overvenus — APPROVED** [review]
:shipit:

**Comment by lucab** [comment]
Published: https://crates.io/crates/prometheus/0.13.2
Tagged: https://github.com/tikv/rust-prometheus/releases/tag/v0.13.2

**Pull request merged**
