### PR TITLE
ci: update linting toolchain to 1.53

### PR DESCRIPTION
**Pull request by lucab**
This updates the linting toolchain to latest stable version and
fixes a couple of new warnings.

### CODE REVIEW

**Comment by lucab** [comment]
@breeswish it looks like Travis is gone. I'll work on porting the remaining jobs to github jobs. In the meanwhile, can you please mark it as non-required to unblock this?

**Comment by lucab** [comment]
I ended up folding the Travis migration into this PR.

**Review by mxinden — APPROVED** [review]
Thanks for cleaning this up!

**Comment by BusyJay** [comment]
@zhouqiang-cl can you help cancel the requirement on travis ci?

**Comment by lucab** [comment]
Thanks all!

**Pull request merged**
