### PR TITLE
process: Add swap memory metrics

### PR DESCRIPTION
**Pull request by quodlibetor**
Related to rss and virtual size, this adds swapped-out memory.

### CODE REVIEW

**Comment by breeswish** [comment]
Thanks for the contribution! The process collector is intentionally to be identical to the official [Golang client implementation](https://github.com/prometheus/client_golang/blob/040c98c8e638eb358dfc1b4b04b385a8df21e6a7/prometheus/process_collector.go). If you would like to report swap memory, maybe it is better to introduce it at the application side?

**Comment by lucab** [comment]
However the `METRICS` typo fix would be to nice to land. @quodlibetor can you please split that to its own PR?

**Comment by quodlibetor** [comment]
Ah, I didn't realize that there was some other client that this was trying to match. Makes sense!

**Comment by quodlibetor** [comment]
> However the METRICS typo fix would be to nice to land.

Moved it to #335

**Pull request closed without merging**
