### PR TITLE
Add warp example

### PR DESCRIPTION
**Pull request by marcelbuesing**
This adds an example that uses warp for serving the metric data. It's based on the hyper example.
Currently still waiting for this PR https://github.com/seanmonstar/warp/pull/336.

### CODE REVIEW

**Comment by breeswish** [comment]
Thanks! Looks like seanmonstar/warp#336 is merged. Would you like to update your PR?

**Comment by mxinden** [comment]
@marcelbuesing @breeswish I don't feel like another example with an http library that is based on the library used in the already existing example is of much help to users. Is there something in particular you would like to stress that is not already explained with https://github.com/tikv/rust-prometheus/blob/master/examples/example_hyper.rs?

**Comment by lucab** [comment]
Additional concern, the more dependencies we add to Cargo manifest (including dev-deps) the bigger it becomes a burden for packagers and distributors to handle. I'd rather go in the other direction, where we try to minimize the set of examples with external dependecies, or move them to a dedicated out-of-tree examples crate.

**Comment by marcelbuesing** [comment]
Sure I can certainly understand the reasoning ! I assume people can still find this PR when searching for this in particular.

**Pull request closed without merging**
