### PR TITLE
Switch to more efficient fd_count() for process_open_fds

### PR DESCRIPTION
**Pull request by bobrik**
Picking up https://github.com/eminence/procfs/pull/105.

For a service with 80k open file descriptors this reduces metric collection time from 500ms down to 100ms (no contention).

### CODE REVIEW

**Comment by bobrik** [comment]
This requires unreleased procfs v0.9.0: https://github.com/eminence/procfs/milestone/1

I'll update the PR once it's ready, please don't merge as is.

**Review by mxinden — COMMENTED** [review]
Thanks for following this all the way through @bobrik. Looks good to me once procfs is released and Cargo.toml is updated.

@lucab I remember you having some improvements for the process collector in mind. Does this change align with those plans?

**Comment by lucab** [comment]
Thanks, I didn't realize `procfs` was also inspecting metadata, this is a good enhancement!

When I was looking at this code I was unhappy about the underlying approach of listing a `/proc` directory just to count FD. Linux kernel could offer a better primitive, but that's still not available. See https://twitter.com/lucabruno/status/1292400305842331649 for some context.

**Comment by eminence** [comment]
Hi.  procfs v0.9.0 is now released with the new `fd_count()` function

**Comment by lucab** [comment]
@bobrik this should be unblocked now, can you please rebase on current `master`?

**Comment by bobrik** [comment]
Rebased

**Review by breeswish — APPROVED** [review]
Thanks!

**Pull request merged**
