### PR TITLE
Allow trailing commas on macros

### PR DESCRIPTION
**Pull request by HyeonuPark**
This PR allows to append optional comma after the last argument of those opts!/register! like macros.

### CODE REVIEW

**Comment by HyeonuPark** [comment]
I guess all I needs to do for the DCO issue is to append the `Signed-off-by:` line to the commit msg. Maybe it was a mistake to make the change directly on the GH web editor, which makes it nontrivial to simply change the commit msg :P

**Comment by lucab** [comment]
@HyeonuPark thanks for the PR! Indeed, your commit should be signed off to pass CI checks. Travis failure is due to https://github.com/tikv/rust-prometheus/pull/391 and should go away if you rebase to latest master.

**Review by lucab — APPROVED** [review]

**Review by breeswish — APPROVED** [review]
Thanks a lot! Could you also supply some unit tests to verify that this syntax pass the compiling? In this way we can avoid some future mistakes :) For example, you can just write a test importing the macro and then use these macros with trailing commas.

**Comment by lucab** [comment]
@HyeonuPark ping, do you plan to come back to this soon-ish?

**Comment by HyeonuPark** [comment]
Sorry for the super late reply! If it's still OK, I'll supplement it within this week.

**Comment by HyeonuPark** [comment]
Shameless copy-pastes from doc comments with additional comma per invocation. :) I can't say anymore it's a tiny change w.r.t. the LoC.

**Comment by HyeonuPark** [comment]
Applied cargo fmt on it.

**Comment by lucab** [comment]
Thanks a lot, LGTM!

**Pull request merged**
