### PR TITLE
Fix: use TokenStream from proc_macro

### PR DESCRIPTION
**Pull request by fggarcia**

### CODE REVIEW

**Comment by mxinden** [comment]
@fggarcia thanks for the patch! Could you sign-off your commit and force-push once more?

See https://github.com/probot/dco#how-it-works.

**Comment by fggarcia** [comment]
@mxinden ready!

**Comment by mxinden** [comment]
Thanks @fggarcia. https://github.com/tikv/rust-prometheus/pull/381 would fix the CI failures.

In case this is very urgent for you to be merged, we might be able to release this before https://github.com/tikv/rust-prometheus/pull/381.

**Comment by fggarcia** [comment]
Hi @mxinden it doesn't urgent. I prefer wait for #381 . Then i will merge that change into my PR.

**Comment by lucab** [comment]
@mxinden #381 is stuck on this fix though. We can either merge one of them manually, or cherry-pick one commit into the other PR, as you prefer.

**Comment by mxinden** [comment]
Merged with https://github.com/tikv/rust-prometheus/pull/381, thanks @fggarcia.

**Pull request closed without merging**
