### PR TITLE
static-metric/benches: Use label_enum and get

### PR DESCRIPTION
**Pull request by mxinden**
> `fn get()` is only available when label is defined by `label_enum`.

### CODE REVIEW

**Comment by lucab** [comment]
@mxinden did you forget a `cargo fmt` pass on this one?

**Review by breeswish — COMMENTED** [review]
Using label enums is more preferred, maybe we can change to benchmark it?

**Comment by mxinden** [comment]
@breeswish done with https://github.com/tikv/rust-prometheus/pull/352/commits/cba45151615b8ab1a012b988ca8e3879028a0f47. Can you take another look?

As a side note: Using enum leads, as expected to a speedup.

```
cargo benchcmp with_string with_enum 
 name                                    with_string ns/iter  with_enum ns/iter  diff ns/iter   diff %  speedup 
 bench_counter_vec                       44                   46                            2    4.55%   x 0.96 
 bench_single_counter                    4                    4                             0    0.00%   x 1.00 
 bench_static_metrics_handwrite_1        4                    4                             0    0.00%   x 1.00 
 bench_static_metrics_handwrite_2        4                    4                             0    0.00%   x 1.00 
 bench_static_metrics_macro              4                    4                             0    0.00%   x 1.00 
 bench_static_metrics_macro_deep         4                    4                             0    0.00%   x 1.00 
 bench_static_metrics_macro_with_lookup  6                    4                            -2  -33.33%   x 1.50
```

**Comment by mxinden** [comment]
@breeswish @lucab would you mind taking another look?

**Review by breeswish — APPROVED** [review]
Cool, thank you!

**Review by lucab — APPROVED** [review]

**Pull request merged**
